baseURL = "/"
disableLanguages = []
disqusShortname = ""
googleAnalytics = ""
languageCode = "en-gb"
languageName = "En"
paginate = "6"
summaryLength = "10"
theme = "github.com/themefisher/twenty-twenty-hugo"
title = "Edward Mason"
[markup.goldmark.renderer]
unsafe = true
[menu]
desktop = []
[[menu.main]]
URL = "/"
name = "Home"
weight = 1
[[menu.main]]
URL = "about"
name = "About"
weight = 2
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 3
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 4
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
author = "Edward Mason"
description = "This is meta description"
[params.banner]
heading = "Edward Mason - Designer, coder and creator"
image = "images/2020-landscape-1-2.png"
[params.blog]
heading = "My latest posts"
[params.call_to_action]
button_label = "Contact Me"
button_url = "contact"
content = ""
enable = true
title = "Contact me for more information."
[params.footer]
address = "Earth"
content = "Website of Edward Mason, designer and creator"
copyright = "Copyright &copy;2021 Edward Mason"
hours = "I don't have any"
title = "About This Site"
[params.gallery]
enable = true
[[params.gallery.gallery_item]]
image = "images/2020-square-2.png"
[[params.gallery.gallery_item]]
image = "images/2020-square-1.png"
[params.social]
email = ""
facebook = ""
instagram = ""
linkedin = ""
twitter = "https://twitter.com/edwardmaason"
yelp = ""
[taxonomies]
author = "author"
category = "categories"
tag = "tags"
